### ISSUE TITLE
update_github() fails on windows R3.2.1

### ISSUE THREAD

**Issue by davidski** [hrbrmstr/dtupdate#3]
A fresh install of `dtupdate` gives:

```> github_update()
Error: subscript out of bounds```

```
> session_info()
Session info ---------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   x86_64, mingw32             
 ui       RStudio (0.99.473)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         

Packages -------------------------------------------
 package    * version    date      
 assertthat   0.1        2013-12-06
 curl         0.9.3      2015-08-25
 DBI          0.3.1      2014-09-24
 devtools   * 1.8.0      2015-05-09
 digest       0.6.8      2014-12-31
 dplyr      * 0.4.2.9002 2015-08-14
 dtupdate   * 1.4        2015-08-27
 git2r        0.11.0     2015-08-12
 htmltools    0.2.6      2014-09-08
 httr       * 1.0.0      2015-06-25
 lazyeval     0.1.10     2015-01-02
 magrittr     1.5        2014-11-22
 memoise      0.2.1      2014-04-22
 R6           2.1.1      2015-08-19
 Rcpp         0.12.0     2015-07-25
 rmarkdown  * 0.7        2015-06-13
 rstudioapi   0.3.1      2015-04-07
 rversions    1.0.2      2015-07-13
 stringi      0.5-5      2015-06-29
 stringr    * 1.0.0      2015-04-30
 xml2         0.1.1      2015-06-02
 source                            
 CRAN (R 3.2.1)                    
 CRAN (R 3.2.2)                    
 CRAN (R 3.2.1)                    
 CRAN (R 3.2.0)                    
 CRAN (R 3.2.1)                    
 Github (hadley/dplyr@b292554)     
 Github (hrbrmstr/dtupdate@7e31a26)
 CRAN (R 3.2.1)                    
 CRAN (R 3.2.1)                    
 CRAN (R 3.2.1)                    
 CRAN (R 3.2.1)                    
 CRAN (R 3.2.1)                    
 CRAN (R 3.2.1)                    
 CRAN (R 3.2.2)                    
 CRAN (R 3.2.1)                    
 CRAN (R 3.2.1)                    
 CRAN (R 3.2.1)                    
 CRAN (R 3.2.1)                    
 CRAN (R 3.2.1)                    
 CRAN (R 3.2.0)                    
 CRAN (R 3.2.1)                    
> 
```

**Comment by hrbrmstr** [comment]
and here i was thinking i was the only one who found said bug ;-)

**Comment by hrbrmstr** [comment]
give 1.5 a spin in ur spare time (pls)

**Comment by davidski** [comment]
Working like a charm! Thanks!

**Comment by hrbrmstr** [comment]
:+1:
